config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create]

  resources :restaurants do
    resources :reviews, only: %i[new create]
  end

  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div>
  <%= form_for @restaurant do |form| %>
  <p><%= form.label :name %></p>
  <%= form.text_field :name %>
  <br>
  <p><%= form.label :address %></p>
  <%= form.text_field :address %>
  <br>
  <p><%= form.label :phone_number %></p>
  <%= form.text_field :phone_number %>
  <br>
  <p><%= form.label :category %></p>
  <%= form.select :category, [['Chinese','chinese'],['Italian','italian'],['Japanese','japanese'],['French','french'],['Belgian','belgian']] %>
  <br>
  <br>
  <%= form.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h2>Restaurants</h2>
<ul>
<% @restaurants.each do |restaurant| %>
<% name = restaurant.name %>
  <li> <p> <strong> <%= link_to name, restaurant %> </strong>  </p>
    <%= restaurant.category.capitalize %> | <%= restaurant.address %> | <%= restaurant.phone_number %> </li> <br>
<% end %>
</ul>

<div>
  <%= link_to("Add new restaurant", new_restaurant_path) %>
</div>

app/views/restaurants/new.html.erb
<h2>Add new restaurant</h2>
<%= render 'form', restaurant: @restaurant %>
<br>
<%= link_to "return", restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<h3><%= @restaurant.category.capitalize %></h3>

<ul>
  <li> Address: <%= @restaurant.address %> </li>
  <li> Phone number: <%= @restaurant.phone_number %> </li>
</ul>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
<br>
<h3>Reviews:</h3>
<ul style="list-style-type:none;">
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.rating %> | <%= review.content %></li>
  <% end %>
</ul>
<%= link_to "Return", restaurants_path %>

app/views/reviews/_form.html.erb
<div>
  <%= simple_form_for [@restaurant, @review] do |form| %>
  <p><%= form.input :content %></p>
  <br>
  <p><%= form.label :rating %></p>
  <%= form.select :rating, [[0,0],[1,1],[2,2],[3,3],[4,4],[5,5]] %>
  <br>
  <br>
  <%= form.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2>Add new review to <%= @restaurant.name %> </h2>
<%= render 'form', review: @review %>
<br>
<%= link_to "Return", restaurant_path(@restaurant) %>